Part A - Data Structure
Explore the following data structures:

List: Create a list of fruit names, add one new fruit, then display the length of the list.

Tuple: Create a tuple containing three to five cities, then display the second city.

Set: Create a set of odd numbers from 1-10, add a new number, then print the contents of the set.

Dictionary: Create a dictionary of student data (name, age, major), then access the value for the major.

In [3]:
fruit = ['apple','orange']
fruit.append('banana')
print(fruit)
print(f"Length of List: {len(fruit)}")

['apple', 'orange', 'banana']
Length of List: 3

In [5]:
cities = ('Jakarta','Surabaya','Bandung')
print(cities[1])

Surabaya

In [6]:
odd_number = {1,3,5,7,9}
odd_number.add(11)
print(odd_number)

{1, 3, 5, 7, 9, 11}

In [7]:
student_data = {
    'name' : 'john',
    'age' : 25,
    'major' : 'computer science'
}

print(student_data['major'])

computer science

Part B – Conditional Statements (if, elif, else)

Use the concepts of if, elif, and else to solve the following problem:

Create a variable for the score.

If the score is ≥ 75, display "Pass".

If the score is between 60-74, display "Remedial".

If the score is < 60, display "Fail".

In [10]:
score = int(input('Enter the score : '))

if score >= 75 :
    print('pass')
elif score >= 60:
    print('remedial')
else :
    print('fail')

pass

Part C – Loops

Use a for loop and a while loop to solve the following problems:

Display the numbers 1 to 10 using a for loop.
Display all elements of the following list:

fruits = ["apple", "orange", "banana", "mango"]

In [12]:
for i in range (1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10

In [13]:
fruits = ["apple", "orange", "banana", "mango"]

for i in fruits:
    print(i)

apple
orange
banana
mango

Part D – Functions

Use the concept of functions to solve the following problem:

Create a function volume_cuboid(length, width, height).

Return the volume result and display it.

In [14]:
def volume_cuboid(length, width, height):
    return length * width * height

volume_cuboid(10,20,15)

3000

Part E – Pandas DataFrame

In this section, we will use a synthetic dataset called tips. Based on this dataset, complete the following problems.

Problem E1: Identify Continuous and Categorical Data and Create a DataFrame

Display the first 5 rows of the DataFrame.
Display the data structure information using the appropriate method (the info method).
Group each column into:
Quantitative Data
Categorical/Qualitative Data
Create a simple DataFrame containing:
Column name
Data type
Data category (quantitative/qualitative)

In [19]:
import pandas as pd

df = pd.read_csv('tips.csv')
print(df.head())

   total_bill    tip     sex smoker   day    time  size
0       13.81   2.52    Male     No   Sat  Dinner     2
1       17.05   3.19    Male    Yes   Sat  Dinner     2
2       10.82   1.94    Male    Yes  Thur   Lunch     2
3       16.12   2.81  Female     No   Sat  Dinner     2
4       42.51  10.00  Female    Yes   Sun  Dinner     4

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [38]:
numeric = df.select_dtypes(include="number").columns

summary = pd.DataFrame({
    "column_name" : df.columns,
    "data_type" : df.dtypes.astype(str).values,
    "category" : ["quantitative" if col in numeric else "qualitative" for col in df.columns] 
})

summary

  column_name data_type      category
0  total_bill   float64  quantitative
1         tip   float64  quantitative
2         sex       str   qualitative
3      smoker       str   qualitative
4         day       str   qualitative
5        time       str   qualitative
6        size     int64  quantitative

Problem E2: Identify Continuous and Categorical Data and Create a DataFrame

Identify all columns in the tips dataset.
For each quantitative column, determine whether it is:
Continuous (can be measured)
Discrete (can be counted)
For each qualitative column, determine whether it is:
Nominal (has no order)
Ordinal (has an order)

In [ ]:
type_column = pd.DataFrame({
    'name_column' : df.columns,
    "category" : ["quantitative" if col in numeric else "qualitative" for col in df.columns],
    "variable_type" : ["Continuous","Continuous","Nominal","Nominal","Ordinal","Nominal","Discrete"]
})

type_column

  name_column      category variable_type
0  total_bill  quantitative     Continous
1         tip  quantitative     Continous
2         sex   qualitative       Nominal
3      smoker   qualitative       Nominal
4         day   qualitative       Ordinal
5        time   qualitative       Nominal
6        size  quantitative      Discrete

Problem E3: Implementing Loops on a DataFrame

Use a for loop to:
Display each column name and its number of unique values
Use a loop to:
Calculate the mean of the numeric/quantitative columns
Display the results one by one
Compare the loop results with the built-in Pandas function (without a loop): df.mean(numeric_only=True)

In [47]:
for col in df.columns:
    print(f"{col} : {df[col].nunique()}")

total_bill : 237
tip : 175
sex : 2
smoker : 2
day : 4
time : 2
size : 6

In [51]:
for col in df.select_dtypes(include="number").columns:
    print(f"{col} : {round(df[col].mean(),2)}")

total_bill : 18.05
tip : 2.85
size : 2.52

In [52]:
df.mean(numeric_only=True)

total_bill    18.050779
tip            2.847869
size           2.520492
dtype: float64

Problem E4: Data Manipulation with Lambda Functions

Use a lambda function to:
Create a new column tip_percentage: (tip / total_bill × 100)
Use a lambda function on a categorical column to:
Change the values of time to:
"Afternoon" if Lunch
"Evening" if Dinner
Display the first 5 rows after the transformation.

In [54]:
df["tip_percentage"] = df.apply(
    lambda x: x["tip"] / x["total_bill"] * 100, axis =1)

df

     total_bill    tip     sex smoker   day    time  size  tip_percentage
0         13.81   2.52    Male     No   Sat  Dinner     2       18.247647
1         17.05   3.19    Male    Yes   Sat  Dinner     2       18.709677
2         10.82   1.94    Male    Yes  Thur   Lunch     2       17.929760
3         16.12   2.81  Female     No   Sat  Dinner     2       17.431762
4         42.51  10.00  Female    Yes   Sun  Dinner     4       23.523877
..          ...    ...     ...    ...   ...     ...   ...             ...
239       13.14   2.43    Male    Yes  Thur   Lunch     2       18.493151
240       10.60   2.06  Female     No   Sat  Dinner     2       19.433962
241       10.54   1.74  Female    Yes   Sun  Dinner     2       16.508539
242       14.08   2.44  Female     No   Sun  Dinner     2       17.329545
243       12.30   1.78    Male    Yes   Sat  Dinner     2       14.471545

[244 rows x 8 columns]

In [57]:
df['time_label'] = df["time"].apply(
    lambda x: "Afternoon" if x == "Lunch" else "Evening"
)

df

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,time_label
0,13.81,2.52,Male,No,Sat,Dinner,2,18.247647,Evening
1,17.05,3.19,Male,Yes,Sat,Dinner,2,18.709677,Evening
2,10.82,1.94,Male,Yes,Thur,Lunch,2,17.929760,Afternoon
3,16.12,2.81,Female,No,Sat,Dinner,2,17.431762,Evening
4,42.51,10.00,Female,Yes,Sun,Dinner,4,23.523877,Evening
...,...,...,...,...,...,...,...,...,...
239,13.14,2.43,Male,Yes,Thur,Lunch,2,18.493151,Afternoon
240,10.60,2.06,Female,No,Sat,Dinner,2,19.433962,Evening
241,10.54,1.74,Female,Yes,Sun,Dinner,2,16.508539,Evening
242,14.08,2.44,Female,No,Sun,Dinner,2,17.329545,Evening
243,12.30,1.78,Male,Yes,Sat,Dinner,2,14.471545,Evening

In [59]:
df.head(5)

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,time_label
0,13.81,2.52,Male,No,Sat,Dinner,2,18.247647,Evening
1,17.05,3.19,Male,Yes,Sat,Dinner,2,18.709677,Evening
2,10.82,1.94,Male,Yes,Thur,Lunch,2,17.929760,Afternoon
3,16.12,2.81,Female,No,Sat,Dinner,2,17.431762,Evening
4,42.51,10.00,Female,Yes,Sun,Dinner,4,23.523877,Evening

# Bonus

In [3]:
student = [["Rina", [90, 85, 80]], ["Tono", [70, 75, 60]], ["Sari", [88, 89, 92]]]

Find students whose average score is above 80

In [6]:
for data in student:
    name = data[0]
    score = data[1]
    avg = sum(score)/len(score)

    if avg > 80:
        print(f"{name} passed with an average score of {avg:.2f}")

Rina passed with an average score of 85.00
Sari passed with an average score of 89.67

Display students who have at least one score below 70

In [7]:
for data in student:
    if any(n < 70 for n in data[1]):
        print(data[0])

Tono

From the student data, display the name of the student with the highest average score

In [11]:
max_avg = 0

for data in student:
    name = data[0]
    score = data[1]
    avg = sum(score) / len(score)
    if avg > max_avg:
        max_avg = avg 

print(f"{name} has the highest average score: {max_avg:.2f}")

Sari has the highest average score: 89.67

In [28]:
transaction = [
    ['TX001', 'Jakarta', 150000],
    ['TX002', 'Bandung', 95000],
    ['TX003', 'Jakarta', 120000],
    ['TX004', 'Surabaya', 200000],
    ['TX005', 'Jakarta', 99000],
    ['TX006', 'Jakarta', 175000],
    ['TX007', 'Medan', 130000]
]

Your tasks:

Create a new list containing only the transactions that come from Jakarta and have a total greater than 100,000.

Sort those transactions by transaction total (from highest to lowest).

Remove (pop) the transaction with the highest value and display its information in this format:

'Largest transaction: TX006 with a total of Rp 175000'

Print all the remaining filtered and sorted transactions, one per line.

In [29]:
transaction_filter = [i for i in transaction if i[1] == 'Jakarta' and i[2] > 100000]

transaction_filter

[['TX001', 'Jakarta', 150000],
 ['TX003', 'Jakarta', 120000],
 ['TX006', 'Jakarta', 175000]]

In [30]:
transaction = sorted(transaction, key=lambda i:i[2], reverse=True)
transaction

[['TX004', 'Surabaya', 200000],
 ['TX006', 'Jakarta', 175000],
 ['TX001', 'Jakarta', 150000],
 ['TX007', 'Medan', 130000],
 ['TX003', 'Jakarta', 120000],
 ['TX005', 'Jakarta', 99000],
 ['TX002', 'Bandung', 95000]]

In [31]:
transaction.pop(0)

['TX004', 'Surabaya', 200000]

In [35]:
print(f"Largest transaction: {transaction[0][0]} with a total of Rp {transaction[0][2]}")

Largest transaction: TX006 with a total of Rp 175000

In [37]:
for i in transaction:
    print(i)

['TX006', 'Jakarta', 175000]
['TX001', 'Jakarta', 150000]
['TX007', 'Medan', 130000]
['TX003', 'Jakarta', 120000]
['TX005', 'Jakarta', 99000]
['TX002', 'Bandung', 95000]

**Judul**: Validasi Formulir Data Peserta

**Deskripsi**:
Kamu diberikan list of dictionary, di mana setiap dictionary merepresentasikan data peserta. Setiap peserta harus memiliki key 'nama', 'usia', dan 'email'.

Tuliskan program untuk:

1. Menampilkan jumlah total peserta.

2. Mengecek berapa peserta yang memiliki data lengkap (semua key ada).

3. Menampilkan daftar nama peserta yang datanya belum lengkap.

In [2]:
# Data
peserta = [
    {'nama': 'Aldi', 'usia': 17, 'email': 'aldi@gmail.com'},
    {'nama': 'Bela', 'usia': 18},
    {'usia': 19, 'email': 'cici@gmail.com'},
    {'nama': 'Dodi', 'usia': 20, 'email': 'dodi@gmail.com'},
]

# Output:
# Total peserta: 4
# Peserta dengan data lengkap: 2
# Peserta tidak lengkap: ['Bela', 'Unknown']

In [5]:
print(f'Total peserta : {len(peserta)}')

Total peserta : 4

In [19]:
peserta_lengkap = 0
tidak_lengkap = []

for i in peserta:
    if 'nama' in i and 'usia' in i and 'email' in i:
        peserta_lengkap += 1
    else :
        nama = i.get('nama','unknown')
        tidak_lengkap.append(nama)

print(f"Peserta dengan peserta lengkap : {peserta_lengkap}")
print(f"Peserta tidak lengkap : {tidak_lengkap}")

Peserta dengan peserta lengkap : 2
Peserta tidak lengkap : ['Bela', 'unknown']

Saat kamu menghadapi data riil seperti transaksi, data siswa, log aktivitas, dll — biasanya data disimpan dalam bentuk struktur yang lebih kompleks seperti list of dictionary.

Menggunakan `loop bersarang` atau `nested loops` dan logika `if`, kamu bisa:

* Mengelompokkan data berdasarkan kategori
* Menjumlahkan atau menghitung berdasarkan kondisi tertentu
* Membuat agregasi sederhana tanpa library tambahan

In [20]:
pengeluaran = [
    {"nama": "Andi", "kategori": "makanan", "jumlah": 50},
    {"nama": "Budi", "kategori": "transportasi", "jumlah": 20},
    {"nama": "Andi", "kategori": "makanan", "jumlah": 30},
    {"nama": "Cici", "kategori": "hiburan", "jumlah": 40},
    {"nama": "Budi", "kategori": "makanan", "jumlah": 25},
]

# Hitung Total Pengeluaran Tiap Orang

In [21]:
rekap = {}

for i in pengeluaran:
    nama = i['nama']
    jumlah = i['jumlah']
    if nama not in rekap:
        rekap[nama] = jumlah 
    else :
        rekap[nama] += jumlah 

print(rekap)

{'Andi': 80, 'Budi': 45, 'Cici': 40}

In [37]:
score = [
    {"mapel": "Matematika", "nilai": 80},
    {"mapel": "Bahasa", "nilai": 75},
    {"mapel": "Matematika", "nilai": 90},
    {"mapel": "Bahasa", "nilai": 65},
    {"mapel": "IPA", "nilai": 85},
]

#Buat dictionary yang menampung rata-rata nilai per mapel

In [43]:
total_nilai = {}
jumlah_data = {}

for i in score:
    mapel = i['mapel']
    nilai = i['nilai']
    if mapel in jumlah_data:
        jumlah_data[mapel] += 1 
        total_nilai[mapel] += nilai
    else :
        jumlah_data[mapel] = 1
        total_nilai[mapel] = nilai 

rata2 = {}

for mapel in total_nilai:
    rata2[mapel] = total_nilai[mapel] / jumlah_data[mapel]

rata2

{'Matematika': 85.0, 'Bahasa': 70.0, 'IPA': 85.0}

In [ ]:
produk = [
    {"nama": "Laptop A", "penjualan": 120, "rating": [4.5, 4.0, 5.0]},
    {"nama": "Laptop B", "penjualan": 75, "rating": [4.2, 4.0]},
    {"nama": "Laptop C", "penjualan": 50, "rating": [3.5, 4.0, 3.8, 4.1]}
]

**Tugas**:


Buat fungsi `total_penjualan(data)` → mengembalikan total penjualan dari seluruh produk.

Buat fungsi `average_rating(data)` → mengembalikan rata-rata dari semua rating gabungan seluruh produk.

In [58]:
def total_penjualan(data):
    total = 0
    for i in data:
        penjualan = i['penjualan']
        total += penjualan 

    return total


total_penjualan([
    {"nama": "Laptop A", "penjualan": 120, "rating": [4.5, 4.0, 5.0]},
    {"nama": "Laptop B", "penjualan": 75, "rating": [4.2, 4.0]},
    {"nama": "Laptop C", "penjualan": 50, "rating": [3.5, 4.0, 3.8, 4.1]}
])

245

In [55]:
def average_rating(data):
    summary_rating = []
    for i in data:
        rating = i['rating']
        summary_rating.append(sum(rating)/len(rating))  
    return sum(summary_rating) / len(summary_rating)

    



average_rating([
    {"nama": "Laptop A", "penjualan": 120, "rating": [4.5, 4.0, 5.0]},
    {"nama": "Laptop B", "penjualan": 75, "rating": [4.2, 4.0]},
    {"nama": "Laptop C", "penjualan": 50, "rating": [3.5, 4.0, 3.8, 4.1]}
])

4.1499999999999995

Buat fungsi `rating_tertinggi(data)` yang:

1. Mengembalikan rating tertinggi dari masing-masing produk.

2. Jika rating kosong atau salah format, tangani dengan try-except.

Gunakan built-in:

* `max()` → ambil nilai tertinggi dari list rating

In [62]:
produk = [
    {"nama": "Produk A", "rating": [4.5, 4.7, 5.0]},
    {"nama": "Produk B", "rating": []},
    {"nama": "Produk C", "rating": [4.1, 4.2]}
]

def rating_tertinggi(produk):
    for i in produk:
        try:
            tertinggi = max(i['rating'])
            print(f'Produk {i['nama']} rating tertingginya : {tertinggi}')
        except ValueError as e :
            print(f'Produk {i['nama']} error {e}')

rating_tertinggi(produk)

Produk Produk A rating tertingginya : 5.0
Produk Produk B error max() iterable argument is empty
Produk Produk C rating tertingginya : 4.2

Buat fungsi `cek_penjualan_minimum(data, ambang)` yang:

1. Mengecek apakah penjualan produk memenuhi ambang minimal (misalnya 100 unit)

2. Jika penjualan < ambang, raise custom exception `PenjualanTerlaluSedikit`

3. Gunakan built-in:

* min() → cari penjualan terendah dari semua produk

In [ ]:
# Data
produk = [
    {"nama": "Produk A", "penjualan": 150},
    {"nama": "Produk B", "penjualan": 80},
    {"nama": "Produk C", "penjualan": 120}
]
def cek_penjualan_minimum(penjualan, batas):
    for i in penjualan:
        jumlah_penjualan = i['penjualan']
        nama = i['nama']
        if jumlah_penjualan < batas:
            raise ValueError (f'{nama} dibawah batas')
        else :
            print('semua produk diatas batas minimum')
        



cek_penjualan_minimum(produk,100)

semua produk diatas batas minimum

ValueError: Produk B dibawah batas